language: groovy

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - sudo add-apt-repository ppa:mmk2410/intellij-idea -y
  - sudo apt-get update -q
  - sudo apt-get install intellij-idea-community -y
  - sudo apt-get install groovy -y

install:
  - ./gradlew assemble
  # - wget https://github.com/bentolor/idea-cli-inspector/archive/master.zip
  # - unzip master.zip
  - sudo chmod -R aog+w /opt/intellij-idea-community/bin

script:
  - ./gradlew check
  # Copy idea configuration template (mostly .IntelliJIdea2018.1/config/options/jdk.table.xml)
  - cp -r ./etc/travis-agent/.IntelliJIdea2018.1 /home/travis/.IdeaIC2018.1
  - ./ideainspect.groovy -i /opt/intellij-idea-community